version: '3.8'

services:
  web-termius:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-termius-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - ENCRYPTION_KEY=my-super-secret-termius-key-2026
    volumes:
      - ./server/data:/app/data
